local HttpService=game:GetService("HttpService")local Players=game:GetService("Players")local CoreGui=game:GetService("CoreGui")local TweenService=game:GetService("TweenService")local UserInputService=game:GetService("UserInputService")local player=Players.LocalPlayer
local keys={"Hubby32192","RealYoah14","Noah#72","Hostas679","ExagonCity17"}local links={"https://loot-link.com/s?fu0TDL8J","https://lootdest.org/s?FwKQ1VJY","https://loot-link.com/s?17SNvNwJ","https://lootdest.org/s?cYGJS3c4","https://loot-link.com/s?Ds3P250e"}
local keyData=nil local pastebinKey="https://pastebin.com/raw/vrJViGzh"local identifier=player.UserId.."-"..tostring(game:GetService("Stats").Network.ServerStatsItem["Data Ping"]:GetValue())local function getSavedKey()local success,response=pcall(function()return HttpService:GetAsync(pastebinKey)end)if success then local data=HttpService:JSONDecode(response)local now=os.time()if data[identifier]and now-data[identifier].timestamp<86400 then return data[identifier].keyIndex end end return nil end
local function saveKey(keyIndex)if keyData==nil then local success,response=pcall(function()return HttpService:GetAsync(pastebinKey)end)if success then keyData=HttpService:JSONDecode(response)else keyData={}end end keyData[identifier]={keyIndex=keyIndex,timestamp=os.time()}pcall(function()HttpService:PostAsync(pastebinKey,HttpService:JSONEncode(keyData),{["Content-Type"]="application/json"})end)end
local savedKeyIndex=getSavedKey()local currentKeyIndex=savedKeyIndex or math.random(1,#keys)saveKey(currentKeyIndex)local currentKey=keys[currentKeyIndex]
local ScreenGui=Instance.new("ScreenGui")ScreenGui.Name="HUBKey"ScreenGui.Parent=CoreGui ScreenGui.ResetOnSpawn=false
local KeyFrame=Instance.new("Frame")KeyFrame.Size=UDim2.new(0,400,0,300)KeyFrame.Position=UDim2.new(0.5,-200,0.5,-150)KeyFrame.BackgroundColor3=Color3.fromRGB(15,15,20)KeyFrame.BorderSizePixel=0 KeyFrame.Parent=ScreenGui
local KeyCorner=Instance.new("UICorner")KeyCorner.CornerRadius=UDim.new(0,15)KeyCorner.Parent=KeyFrame
local KeyStroke=Instance.new("UIStroke")KeyStroke.Color=Color3.fromRGB(0,200,255)KeyStroke.Thickness=2 KeyStroke.Transparency=0.3 KeyStroke.Parent=KeyFrame
local Gradient=Instance.new("UIGradient")Gradient.Color=ColorSequence.new{ColorSequenceKeypoint.new(0,Color3.fromRGB(0,200,255)),ColorSequenceKeypoint.new(1,Color3.fromRGB(0,150,200))}Gradient.Rotation=45 Gradient.Parent=KeyFrame
local Title=Instance.new("TextLabel")Title.Size=UDim2.new(1,0,0,60)Title.BackgroundTransparency=1 Title.Text="🔑 HUB KEY SYSTEM"Title.TextColor3=Color3.fromRGB(255,255,255)Title.TextScaled=true Title.Font=Enum.Font.GothamBold Title.Parent=KeyFrame
Title.Position=UDim2.new(0,0,0,20)
local SubTitle=Instance.new("TextLabel")SubTitle.Size=UDim2.new(1,-40,0,30)SubTitle.Position=UDim2.new(0,20,0,80)SubTitle.BackgroundTransparency=1 SubTitle.Text="Your Key: "..currentKey SubTitle.TextColor3=Color3.fromRGB(200,200,200)SubTitle.TextScaled=true SubTitle.Font=Enum.Font.Gotham SubTitle.TextXAlignment=Enum.TextXAlignment.Left SubTitle.Parent=KeyFrame
local GetKeyBtn=Instance.new("TextButton")GetKeyBtn.Size=UDim2.new(0.9,0,0,40)GetKeyBtn.Position=UDim2.new(0.05,0,0,120)GetKeyBtn.BackgroundColor3=Color3.fromRGB(50,50,60)GetKeyBtn.Text="Get Key "..currentKey.." Here"GetKeyBtn.TextColor3=Color3.fromRGB(255,255,255)GetKeyBtn.TextScaled=true GetKeyBtn.Font=Enum.Font.GothamSemibold GetKeyBtn.Parent=KeyFrame
local GetKeyCorner=Instance.new("UICorner")GetKeyCorner.CornerRadius=UDim.new(0,10)GetKeyCorner.Parent=GetKeyBtn
local KeyInput=Instance.new("TextBox")KeyInput.Size=UDim2.new(0.9,0,0,50)KeyInput.Position=UDim2.new(0.05,0,0,180)KeyInput.BackgroundColor3=Color3.fromRGB(30,30,40)KeyInput.PlaceholderText="Put Your Key Here..."KeyInput.Text=""KeyInput.TextColor3=Color3.fromRGB(255,255,255)KeyInput.PlaceholderColor3=Color3.fromRGB(150,150,150)KeyInput.TextScaled=true KeyInput.Font=Enum.Font.Gotham KeyInput.Parent=KeyFrame
local KeyInputCorner=Instance.new("UICorner")KeyInputCorner.CornerRadius=UDim.new(0,10)KeyInputCorner.Parent=KeyInput
local VerifyBtn=Instance.new("TextButton")VerifyBtn.Size=UDim2.new(0.9,0,0,50)VerifyBtn.Position=UDim2.new(0.05,0,0,240)VerifyBtn.BackgroundColor3=Color3.fromRGB(100,100,100)VerifyBtn.Text="VERIFY KEY"VerifyBtn.TextColor3=Color3.fromRGB(200,200,200)VerifyBtn.TextScaled=true VerifyBtn.Font=Enum.Font.GothamBold VerifyBtn.Parent=KeyFrame
local VerifyCorner=Instance.new("UICorner")VerifyCorner.CornerRadius=UDim.new(0,10)VerifyCorner.Parent=VerifyBtn
local verified=false
GetKeyBtn.MouseButton1Click:Connect(function()game:GetService("GuiService"):AddSelectionParent("LinkFrame",GetKeyBtn)loadstring(game:HttpGet(links[currentKeyIndex]))()end)
VerifyBtn.MouseButton1Click:Connect(function()if KeyInput.Text==currentKey and not verified then verified=true VerifyBtn.BackgroundColor3=Color3.fromRGB(0,255,200)VerifyBtn.TextColor3=Color3.new(1,1,1)VerifyBtn.Text="✅ VERIFIED!"KeyFrame:TweenPosition(UDim2.new(0.5,-200,2,0),"Out","Quad",0.5,true)wait(0.5)KeyFrame:Destroy()loadHub()else KeyInput.Text=""end end)
function loadHub()local MainGui=Instance.new("ScreenGui")MainGui.Name="ModernHUB"MainGui.Parent=CoreGui MainGui.ResetOnSpawn=false
local MainFrame=Instance.new("Frame")MainFrame.Size=UDim2.new(0,650,0,450)MainFrame.Position=UDim2.new(0.5,-325,0.5,-225)MainFrame.BackgroundColor3=Color3.fromRGB(18,18,25)MainFrame.BorderSizePixel=0 MainFrame.Parent=MainGui
local MainCorner=Instance.new("UICorner")MainCorner.CornerRadius=UDim.new(0,16)MainCorner.Parent=MainFrame
local MainStroke=Instance.new("UIStroke")MainStroke.Color=Color3.fromRGB(0,210,255)MainStroke.Thickness=2 MainStroke.Transparency=0.2 MainStroke.Parent=MainFrame
local MainGradient=Instance.new("UIGradient")MainGradient.Color=ColorSequence.new{ColorSequenceKeypoint.new(0,Color3.fromRGB(0,210,255)),ColorSequenceKeypoint.new(1,Color3.fromRGB(0,160,200))}MainGradient.Rotation=90 MainGradient.Parent=MainFrame
local TitleBar=Instance.new("Frame")TitleBar.Size=UDim2.new(1,0,0,45)TitleBar.BackgroundColor3=Color3.fromRGB(12,12,18)TitleBar.Parent=MainFrame
local TitleCorner=Instance.new("UICorner")TitleCorner.CornerRadius=UDim.new(0,16)TitleCorner.Parent=TitleBar
local TitleLabel=Instance.new("TextLabel")TitleLabel.Size=UDim2.new(1,-60,1,0)TitleLabel.BackgroundTransparency=1 TitleLabel.Text="🚀 MODERN ROBLOX HUB"TitleLabel.TextColor3=Color3.fromRGB(255,255,255)TitleLabel.TextScaled=true TitleLabel.Font=Enum.Font.GothamBlack TitleLabel.TextXAlignment=Enum.TextXAlignment.Left TitleLabel.Position=UDim2.new(0,20,0,0)TitleLabel.Parent=TitleBar
local CloseButton=Instance.new("TextButton")CloseButton.Size=UDim2.new(0,40,0,40)CloseButton.Position=UDim2.new(1,-45,0,2.5)CloseButton.BackgroundColor3=Color3.fromRGB(255,60,60)CloseButton.Text="✕"CloseButton.TextColor3=Color3.fromRGB(255,255,255)CloseButton.TextScaled=true CloseButton.Font=Enum.Font.GothamBold CloseButton.Parent=TitleBar
local CloseCorner=Instance.new("UICorner")CloseCorner.CornerRadius=UDim.new(0,10)CloseCorner.Parent=CloseButton
local dragging=false local dragStart,startPos=nil,nil
TitleBar.InputBegan:Connect(function(input)if input.UserInputType==Enum.UserInputType.MouseButton1 then dragging=true dragStart=input.Position startPos=MainFrame.Position end end)TitleBar.InputChanged:Connect(function(input)if dragging and input.UserInputType==Enum.UserInputType.MouseMovement then local delta=input.Position-dragStart MainFrame.Position=UDim2.new(startPos.X.Scale,startPos.X.Offset+delta.X,startPos.Y.Scale,startPos.Y.Offset+delta.Y)end end)UserInputService.InputEnded:Connect(function(input)if input.UserInputType==Enum.UserInputType.MouseButton1 then dragging=false end end)
CloseButton.MouseButton1Click:Connect(function()MainGui:Destroy()end)
local TabContainer=Instance.new("Frame")TabContainer.Size=UDim2.new(1,0,0,50)TabContainer.Position=UDim2.new(0,0,0,45)TabContainer.BackgroundColor3=Color3.fromRGB(25,25,35)TabContainer.Parent=MainFrame
local ContentContainer=Instance.new("Frame")ContentContainer.Size=UDim2.new(1,-20,1,-115)ContentContainer.Position=UDim2.new(0,10,0,60)ContentContainer.BackgroundTransparency=1 ContentContainer.Parent=MainFrame
local tabs={"SearchBlox","Obfuscator","Executor","PlayerGUI"}local tabButtons={}local tabContents={}
for i,v in ipairs(tabs)do local tabBtn=Instance.new("TextButton")tabBtn.Name="Tab"..i tabBtn.Size=UDim2.new(1/#tabs-0.005,0,1,0)tabBtn.Position=UDim2.new((i-1)/#tabs,5,0,0)tabBtn.BackgroundColor3=Color3.fromRGB(40,40,55)tabBtn.Text=v tabBtn.TextColor3=Color3.fromRGB(220,220,220)tabBtn.TextScaled=true tabBtn.Font=Enum.Font.GothamSemibold tabBtn.Parent=TabContainer
local btnCorner=Instance.new("UICorner")btnCorner.CornerRadius=UDim.new(0,12)btnCorner.Parent=tabBtn tabButtons[i]=tabBtn
local content=Instance.new("ScrollingFrame")content.Name="Content"..i content.Size=UDim2.new(1,0,1,0)content.BackgroundTransparency=1 content.Visible=i==1 content.ScrollBarThickness=6 content.ScrollBarImageColor3=Color3.fromRGB(0,200,255)content.Parent=ContentContainer content.CanvasSize=UDim2.new(0,0,0,0)tabContents[i]=content end
for i,btn in ipairs(tabButtons)do btn.MouseButton1Click:Connect(function()for j,b in ipairs(tabButtons)do b.BackgroundColor3=Color3.fromRGB(40,40,55)tabContents[j].Visible=j==i end btn.BackgroundColor3=Color3.fromRGB(0,210,255)end)end tabButtons[1].BackgroundColor3=Color3.fromRGB(0,210,255)
local function createModernButton(parent,text,pos,size,cbk)local btn=Instance.new("TextButton")btn.Size=size or UDim2.new(0.9,0,0,45)btn.Position=pos or UDim2.new(0.05,0,0,10)btn.BackgroundColor3=Color3.fromRGB(35,35,50)btn.Text=text btn.TextColor3=Color3.fromRGB(255,255,255)btn.TextScaled=true btn.Font=Enum.Font.GothamSemibold btn.Parent=parent local btnC=Instance.new("UICorner")btnC.CornerRadius=UDim.new(0,12)btnC.Parent=btn local btnG=Instance.new("UIGradient")btnG.Color=ColorSequence.new{ColorSequenceKeypoint.new(0,Color3.fromRGB(45,45,65)),ColorSequenceKeypoint.new(1,Color3.fromRGB(25,25,45))}btnG.Parent=btn btn.MouseButton1Click:Connect(cbk)return btn end
local searchFrame=tabContents[1]local searchBox=Instance.new("TextBox")searchBox.Size=UDim2.new(0.9,0,0,40)searchBox.Position=UDim2.new(0.05,0,0,10)searchBox.BackgroundColor3=Color3.fromRGB(30,30,45)searchBox.PlaceholderText="Search ScriptBlox..."searchBox.Text=""searchBox.TextColor3=Color3.fromRGB(255,255,255)searchBox.PlaceholderColor3=Color3.fromRGB(170,170,170)searchBox.TextScaled=true searchBox.Font=Enum.Font.Gotham searchBox.Parent=searchFrame local sCorner=Instance.new("UICorner")sCorner.CornerRadius=UDim.new(0,12)sCorner.Parent=searchBox
createModernButton(searchFrame,"🔍 Search",UDim2.new(0.05,0,0,60),UDim2.new(0.9,0,0,45),function()searchFrame:ClearAllChildren()local query=searchBox.Text if query==""then return end local success,response=pcall(function()return game:HttpGet("https://scriptblox.com/api/script/search?q="..query)end)if success then local data=HttpService:JSONDecode(response)local scripts=data.result.scripts searchFrame.CanvasSize=UDim2.new(0,0,0,#scripts*70)for i,script in ipairs(scripts)do createModernButton(searchFrame,script.title,UDim2.new(0,10,0,(i-1)*70+120),UDim2.new(1,-20,0,60),function()loadstring(script.script or game:HttpGet("https://scriptblox.com/script/"..script.slug.."/raw"))()end)end end end)
local obfFrame=tabContents[2]local codeBox=Instance.new("TextBox")codeBox.Size=UDim2.new(0.9,0,0.4,-20)codeBox.Position=UDim2.new(0.05,0,0,10)codeBox.BackgroundColor3=Color3.fromRGB(25,25,40)codeBox.MultiLine=true codeBox.TextWrapped=true codeBox.PlaceholderText="Lua code..."codeBox.Text=""codeBox.TextColor3=Color3.fromRGB(255,255,255)codeBox.Font=Enum.Font.Gotham codeBox.TextScaled=false codeBox.TextYAlignment=Enum.TextYAlignment.Top codeBox.Parent=obfFrame local obfCorner=Instance.new("UICorner")obfCorner.CornerRadius=UDim.new(0,12)obfCorner.Parent=codeBox
local obfLvl=Instance.new("TextBox")obfLvl.Size=UDim2.new(0.45,0,0,35)obfLvl.Position=UDim2.new(0.05,0,0.42,0)obfLvl.BackgroundColor3=Color3.fromRGB(30,30,45)obfLvl.PlaceholderText="Obf Level"obfLvl.Text="1"obfLvl.Parent=obfFrame local lvlCorner=Instance.new("UICorner")lvlCorner.CornerRadius=UDim.new(0,8)lvlCorner.Parent=obfLvl
local deobAcc=Instance.new("TextBox")deobAcc.Size=UDim2.new(0.45,0,0,35)deobAcc.Position=UDim2.new(0.52,0,0.42,0)deobAcc.BackgroundColor3=Color3.fromRGB(30,30,45)deobAcc.PlaceholderText="Deob Acc"deobAcc.Text="1"deobAcc.Parent=obfFrame local accCorner=Instance.new("UICorner")accCorner.CornerRadius=UDim.new(0,8)accCorner.Parent=deobAcc
local outputBox=Instance.new("TextBox")outputBox.Size=UDim2.new(0.9,0,0.55,-80)outputBox.Position=UDim2.new(0.05,0,0.5,10)outputBox.BackgroundColor3=Color3.fromRGB(25,25,40)outputBox.MultiLine=true outputBox.TextWrapped=true outputBox.PlaceholderText="Output..."outputBox.TextColor3=Color3.fromRGB(0,255,150)outputBox.Font=Enum.Font.Gotham outputBox.TextScaled=false outputBox.TextYAlignment=Enum.TextYAlignment.Top outputBox.Parent=obfFrame local outCorner=Instance.new("UICorner")outCorner.CornerRadius=UDim.new(0,12)outCorner.Parent=outputBox
local function obf(code,lvl)local t={}for i=1,#code do t[i]=string.byte(code,i)end local str=""for _=1,lvl do str=""for _,b in ipairs(t)do str=str.."\\"..b end t={}for i=1,#str do t[i]=string.byte(str,i)end end return'loadstring(" '..str..' ")() 'end
local function deob(code,acc)code=code:gsub("\\(%d+)",function(n)return string.char(tonumber(n))end)code=code:gsub('loadstring%("([^"]+)"%)%(%)$','%1')for i=1,acc do code=code:gsub("([%a_][%w_]*)",function(v)return"_ "..v end)end code=code:gsub(";","\n"):gsub("function","\nfunction"):gsub("end","\nend"):gsub("%s+"," "):gsub("(%s) ","%1")return code end
createModernButton(obfFrame,"🔐 Obfuscate",UDim2.new(0.05,0,0.48,0),UDim2.new(0.44,0,0,40),function()local code=codeBox.Text local lvl=tonumber(obfLvl.Text)or 1 outputBox.Text=obf(code,lvl)end)createModernButton(obfFrame,"🔓 Deobfuscate",UDim2.new(0.52,0,0.48,0),UDim2.new(0.44,0,0,40),function()local code=codeBox.Text local acc=tonumber(deobAcc.Text)or 1 outputBox.Text=deob(code,acc)end)
local execFrame=tabContents[3]local execBox=Instance.new("TextBox")execBox.Size=UDim2.new(0.9,0,0.85,-20)execBox.Position=UDim2.new(0.05,0,0,10)execBox.BackgroundColor3=Color3.fromRGB(25,25,40)execBox.MultiLine=true execBox.TextWrapped=true execBox.PlaceholderText="Execute any Lua..."execBox.Text=""execBox.TextColor3=Color3.fromRGB(255,255,200)execBox.Font=Enum.Font.Gotham execBox.TextScaled=false execBox.TextYAlignment=Enum.TextYAlignment.Top execBox.Parent=execFrame local execCorner=Instance.new("UICorner")execCorner.CornerRadius=UDim.new(0,12)execCorner.Parent=execBox
createModernButton(execFrame,"▶️ Execute",UDim2.new(0.05,0,0.87,0),UDim2.new(0.44,0,0,40),function()local code=execBox.Text code=code:gsub("^%s*(loadstring%([^%)]+%)%([^%)]+%)%s*$","%1")code=code:gsub("^%s*load%(([^%)]+)%)%s*$","loadstring(%1)()")local func,err=loadstring(code)if func then func()else game.StarterGui:SetCore("SendNotification",{Title="Exec Error",Text=tostring(err),Duration=3})end end)createModernButton(execFrame,"🗑️ Clear",UDim2.new(0.52,0,0.87,0),UDim2.new(0.44,0,0,40),function()execBox.Text=""end)
local guiFrame=tabContents[4]local guiList=Instance.new("ScrollingFrame")guiList.Size=UDim2.new(0.9,0,0.9,-60)guiList.Position=UDim2.new(0.05,0,0,10)guiList.BackgroundColor3=Color3.fromRGB(30,30,45)guiList.ScrollBarThickness=6 guiList.ScrollBarImageColor3=Color3.fromRGB(0,210,255)guiList.Parent=guiFrame local guiLCorner=Instance.new("UICorner")guiLCorner.CornerRadius=UDim.new(0,12)guiLCorner.Parent=guiList
local function refreshGUIs()guiList:ClearAllChildren()guiList.CanvasSize=UDim2.new(0,0,0,0)for _,gui in ipairs(player.PlayerGui:GetChildren())do if gui:IsA("ScreenGui")or gui:IsA("SurfaceGui")then local guiBtn=createModernButton(guiList,gui.Name.." ("..gui.ClassName..")",UDim2.new(0,10,0,0),UDim2.new(1,-20,0,50),function()gui:Destroy()refreshGUIs()end)guiList.CanvasSize=UDim2.new(0,0,0,guiList.CanvasSize.Y.Offset+60)end end end createModernButton(guiFrame,"🔄 Refresh GUIs",UDim2.new(0.05,0,0.92,0),UDim2.new(0.9,0,0,40),refreshGUIs)refreshGUIs()
local remotes={"Bypass","Backdoor","ServerSide"}for _,name in ipairs(remotes)do local remote=Instance.new("RemoteEvent")remote.Name=name local folder=game.ReplicatedStorage:FindFirstChild("RemoteEvents")or Instance.new("Folder")folder.Name="RemoteEvents"folder.Parent=game.ReplicatedStorage remote.Parent=folder end end
